#spring:
#  application:
#    name: spring-cloud-ribbon

#spring.data.mongodb.uri: mongodb://localhost/ebanking
 
#server:
#  port: 9999
 
#abonne:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:9092,localhost:9999
#    ServerListRefreshInterval: 15000